trigger:
- main
- conquest

resources:
- repo: self

variables:
  imageName: 'edge_conquest'
  imageVersion: 'v0.7.1'
  registryName: 'iotimageacr'
  dockerfilePath: './Dockerfile'
  pipelineAcrConnection: 'iotacr'

stages:
- stage: Build
  displayName: Build and push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: 'buildAndPush'
        repository: '$(registryName).azurecr.io/$(imageName):$(imageVersion)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(pipelineAcrConnection)'
        tags: '$(imageVersion)'
