apiVersion: apps/v1
kind: Deployment
metadata:
  name: conquest-dicom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conquest-dicom
  template:
    metadata:
      labels:
        app: conquest-dicom
    spec:
      containers:
      - name: conquest-dicom
        image: conquest-dicom:latest
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: conquest-dicom
spec:
  selector:
    app: conquest-dicom
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conquest-dicom
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: conquestdicom.your-domain.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: conquest-dicom
            port:
              number: 5678
