# File: templates/build.yml
steps:
- task: Docker@2
  displayName: 'Build Image'
  inputs:
    command: 'build'
    repository: '$(registryName).azurecr.io/$(imageName)'
    dockerfile: '$(dockerfilePath)'
    containerRegistry: '$(pipelineAcrConnection)'
    tags: '$(imageVersion)'    