# File: templates/build.yml
parameters:
  imageName: ''
  imageVersion: ''
  imagePath: ''
  dockerFilePath: ''
  registryName: ''
  pipelineAcrConnection: ''
steps:
- task: Docker@2
  displayName: 'Build Image'
  inputs:
    command: 'build'
    repository: '${{ parameters.registryName }}.azurecr.io/${{ parameters.imageName }}'
    dockerfile: '${{ parameters.dockerFilePath }}'
    containerRegistry: '${{ parameters.pipelineAcrConnection }}'
    tags: '${{ parameters.imageVersion }}'