trigger:
  - main

  variables:
    imageName: 'd2c-prcoessor-backend'
    imageVersion: 'd2c-prcoessor-backend'
    registryName: 'szdevopslabscr.azurecr.io'
    dockerfilePath: '/src/backend/dotnet/d2c-processor/Dockerfile'
stages:
- stage: BuildAndPush
  displayName: Build and push Docker image
  jobs:
  - job: BuildAndPushJob
    displayName: Build and push job
    pool:
      name: Default
      agent.name: szPrivateBastion2 
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        containerRegistry: '$(registryName)'
        command: 'login'
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: '$(registryName)'
        repository: '$(registryName)/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
  
  # steps:
  # - task: Docker@2
  #   displayName: Build an image
  #   inputs:
  #     repository: $(imageName)
  #     command: build
  #     Dockerfile: app/Dockerfile

export TOKEN=$(az acr login --name $acrName --expose-token --output tsv --query accessToken)
export loginServer=$(az acr login --name $acrName --expose-token --output tsv --query loginServer)
docker login $loginServer --username 00000000-0000-0000-0000-000000000000 --password $TOKEN