name: tester

trigger:
# - none
# - main
- $(Build.SourceBranchName)

pool:
  vmImage: ubuntu-latest

jobs:
- job: MyVar
  steps:
  - bash: |
     echo "##vso[task.setvariable variable=myVar;]myvar1"
    name: "SetMyVar"
  - bash: |
      echo "You can use macro syntax for variables: $(myVar)"
    name: "PrintMyVar"
    