apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jnjiotd2cprocessor
spec:
  serviceName: jnjiotd2cprocessor
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: jnjiotbackend
        image: szdevopslabscr.azurecr.io/d2c-processor-backend:0.4
        env:
        - name: IOTHUB_CONNECTION_STRING
          value: "HostName=szlabs-iot-hub.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=dMBNypodzUSWPbxTXdWaV4PxJTR3jCwehPFCQn+XJXc="
        - name: IOTHUB_EVENT_HUB_COMPATIBLE_ENDPOINT
          value: "Endpoint=sb://iothub-ns-szlabs-iot-24863501-f5f2fbc92a.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=XMuOJh0spASmuLLKcdvBJ8zqjirW6XX1NAgxu1hSXf4=;EntityPath=szlabs-iot-hub"
        - name: IOTHUB_EVENT_HUB_COMPATIBLE_PATH
          value: "szlabs-iot-hub"
        - name: STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=szlaaa12026ce;AccountKey=ZCspYG/5HjJTVdY+9Hf/ZkzHHspd2BGXH8cVPUkgDzmvA5JCyRWk5B6aFG1izNq7YC+i/VsDrxOb+AStciDLcw==;EndpointSuffix=core.windows.net"
        - name: BLOB_CONTAINER_NAME
          value: "iot-firmware"
        # - name: PARTITION_ID
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.name
        # - name: SECRET_NAMESPACE
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: iottwinsecret
type: Opaque
stringData:
  signKey: |
    -----BEGIN PRIVATE KEY-----
    .
    -----END PRIVATE KEY-----


