apiVersion: v1
kind: ServiceAccount
metadata:
  name: jnjiotd2cprocessor-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jnjiotd2cprocessor-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jnjiotd2cprocessor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jnjiotd2cprocessor-role
subjects:
- kind: ServiceAccount
  name: jnjiotd2cprocessor-serviceaccount
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jnjiotd2cprocessor
spec:
  serviceName: jnjiotd2cprocessor
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: jnjiotd2cprocessor-serviceaccount
      containers:
      - name: jnjiotbackend
        image: szdevopslabscr.azurecr.io/d2c-processor-backend:0.6
        env:
        - name: IOTHUB_CONNECTION_STRING
          value: "HostName=szlabs-iot-hub.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=dMBNypodzUSWPbxTXdWaV4PxJTR3jCwehPFCQn+XJXc="
        - name: IOTHUB_EVENT_HUB_COMPATIBLE_ENDPOINT
          value: "Endpoint=sb://iothub-ns-szlabs-iot-24863501-f5f2fbc92a.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=XMuOJh0spASmuLLKcdvBJ8zqjirW6XX1NAgxu1hSXf4=;EntityPath=szlabs-iot-hub"
        - name: IOTHUB_EVENT_HUB_COMPATIBLE_PATH
          value: "szlabs-iot-hub"
        - name: STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=szlaaa12026ce;AccountKey=ZCspYG/5HjJTVdY+9Hf/ZkzHHspd2BGXH8cVPUkgDzmvA5JCyRWk5B6aFG1izNq7YC+i/VsDrxOb+AStciDLcw==;EndpointSuffix=core.windows.net"
        - name: BLOB_CONTAINER_NAME
          value: "iot-firmware"
        - name: SIGNING_PEM
          value: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQml5QWE3YVJIRkRDaDJxZ2EKOXNUVUdJTkU1akhBRm5tTTh4V2VUL3VuaTVJNHROcWhWNVh4MHBEcm1DVjltYnJvRnRmRWEwWFZmS3VNQXh4ZgpaNkxNL3lLaGdZa0RnWVlBQkFHQnpnZG5QNzk4RnNMdVdZVEREUUE3YzByM0JWazhOblJVU2V4cFFVc1JpbFBOCnYzU2NoTzBsUnc5UnU4Nngxa2huVkR4K2R1cTRCaURGY3ZsU0FjeWpMQUNKdmp2b3lUTEppQStUUUZkbXJlYXIKak1pWk5FMjVwVDJ5V1AxTlVuZEp4UGN2VnRmQlc0OGtQT212a1k0V2xxUDViQXdDWHdic0tyQ2drNnhic3AxMgpldz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
        # - name: PARTITION_ID
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.name
        # - name: SECRET_NAMESPACE
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: iottwinsecret
type: Opaque
stringData:
  signKey: |
    -----BEGIN PRIVATE KEY-----
    MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIBiyAa7aRHFDCh2qga
    9sTUGINE5jHAFnmM8xWeT/uni5I4tNqhV5Xx0pDrmCV9mbroFtfEa0XVfKuMAxxf
    Z6LM/yKhgYkDgYYABAGBzgdnP798FsLuWYTDDQA7c0r3BVk8NnRUSexpQUsRilPN
    v3SchO0lRw9Ru86x1khnVDx+duq4BiDFcvlSAcyjLACJvjvoyTLJiA+TQFdmrear
    jMiZNE25pT2yWP1NUndJxPcvVtfBW48kPOmvkY4WlqP5bAwCXwbsKrCgk6xbsp12
    ew==
    -----END PRIVATE KEY-----


