apiVersion: apps/v1
kind: Deployment
metadata:
  name: firmware-update-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-update-microservice
  template:
    metadata:
      labels:
        app: firmware-update-microservice
    spec:
      containers:
        - name: firmware-update-microservice
          image: <your-docker-image>
          env:
            - name: IOTHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: iothub-connection-string-secret
                  key: connection-string
            - name: STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: storage-connection-string-secret
                  key: connection-string
            - name: BLOB_CONTAINER_NAME
              value: <your-blob-container-name>
            # - name: D2C_PARTITION_ID
            #   value: "0"  # Replace with the desired partition ID, or remove this entry to listen to all partitions

