apiVersion: v1
kind: Namespace
metadata:
  name: conquest-dicom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: conquest-dicom
  name: conquest-dicom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conquest-dicom
  template:
    metadata:
      labels:
        app: conquest-dicom
    spec:
      containers:
      - name: conquest-dicom
        image: iotimageacr.azurecr.io/edge_conquest:0.7.2
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  namespace: conquest-dicom
  name: conquest-dicom-service
spec:
  selector:
    app: conquest-dicom
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: conquest-dicom
  name: conquest-dicom-ingress
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: /api/version
    appgw.ingress.kubernetes.io/use-private-ip: 'true'
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: azure-application-gateway
  rules:
  # - host: conquest-dicom.mydomain.com
  - http:
      paths:
      - pathType: Prefix
        path: "/dicom"
        backend:
          service:
            name: conquest-dicom-service
            port:
              number: 5678
