apiVersion: policy.openservicemesh.io/v1alpha1
kind: IngressBackend
metadata:
  name: cloudpillar-services-ingress-backend
spec:
  backends:
    {{- range .Values.controllers }}
    {{- if and .port .path }}
    - name: cloudpillar{{ .service }}-service
      port:
        number: {{ .port }}
        protocol: http
      tls:
        skipClientCertValidation: false
    {{- end }}
    {{- end }}
  sources:
    - kind: IPRange
      name: 10.22.0.0/15
    - kind: Service
      name: traefik
      namespace: traefik