apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: /api/version
    appgw.ingress.kubernetes.io/use-private-ip: 'true'
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      {{- range .Values.controllers }}
      {{- if and .port .path }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .title }}-service
            port:
              number: {{ .port }}
      {{- end }}
      {{- end }}
