{{- range .Values.controllers }}
{{- if and .port .path .expose }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .title }}-headers
spec:
  headers:
    customRequestHeaders:
      Host: {{ .title }}-service.cp-be-ns.svc
{{- end }}
{{- end }}
