# Default values for cartonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controllers:
  - title: "analyzer"
  - title: "beapi"
    path: /cloudpillar/api
    port: 8089
  - title: "blobstreamer"
    port: 8089
    env:
    - name: BlobContainerName
      value: "iotcontainer"
    - name: IothubConnectionString
      value: "HostName=iot-dicom-dev-hub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=E2XYLv9hvVVnlq0Kq4albyb3BGcYQiMW2qvgGAqjEZ4="
    - name: StorageConnectionString
      value: "DefaultEndpointsProtocol=https;AccountName=iotdicomdevstorage;AccountKey=q6rFgRGKo0+BxrtcbTSGUFNEFF4av7nkS6Fghy0LaIQ5+K9Bs+BsjVDLRP58MN8QrP58gdcQHwBa+AStT/Llhw==;EndpointSuffix=core.windows.net"
    - name: MessageExpiredMinutes
      value: "60"
    - name: RetryPolicyBaseDelay
      value: "2"
    - name: RetryPolicyExponent
      value: "3"
    # - name: PARTITION_ID
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.name
    # - name: SECRET_NAMESPACE
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.namespace
  - title: "iotlistener"
    kind: StatefulSet
    env:
    - name: LogswriteTopic
      value: "logswrite-topic"
    - name: IothubEventHubCompatibleEndpoint
      value: "Endpoint=sb://iothub-ns-iot-dicom-24995834-325eff99c6.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=E2XYLv9hvVVnlq0Kq4albyb3BGcYQiMW2qvgGAqjEZ4=;EntityPath=iot-dicom-dev-hub"
    - name: IothubEventHubCompatiblePath
      value: "iot-dicom-dev-hub"
    - name: StorageConnectionString
      value: "DefaultEndpointsProtocol=https;AccountName=iotdicomdevstorage;AccountKey=q6rFgRGKo0+BxrtcbTSGUFNEFF4av7nkS6Fghy0LaIQ5+K9Bs+BsjVDLRP58MN8QrP58gdcQHwBa+AStT/Llhw==;EndpointSuffix=core.windows.net"
    - name: BlobContainerName
      value: "iotcontainer"
    - name: BlobStreamerUrl
      value: "blobstreamer-service"
    - name: SigningUrl
      value: "signing-service"
    - name: RangeCalculateType
      value: "percent"
    - name: RangePercent
      value: "25"
    - name: MessageTimeoutMinutes
      value: "60"
    - name: RangeBytes
      value: "123456"
    - name: IothubConnectionDeviceId
      value: "iothub-connection-device-id"     
  - title: "keyholder"
    port: 8089
    env:
    - name: KubernetesServiceHost
      value: ""
    - name: SigningPem
      value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQml5QWE3YVJIRkRDaDJxZ2EKOXNUVUdJTkU1akhBRm5tTTh4V2VUL3VuaTVJNHROcWhWNVh4MHBEcm1DVjltYnJvRnRmRWEwWFZmS3VNQXh4ZgpaNkxNL3lLaGdZa0RnWVlBQkFHQnpnZG5QNzk4RnNMdVdZVEREUUE3YzByM0JWazhOblJVU2V4cFFVc1JpbFBOCnYzU2NoTzBsUnc5UnU4Nngxa2huVkR4K2R1cTRCaURGY3ZsU0FjeWpMQUNKdmp2b3lUTEppQStUUUZkbXJlYXIKak1pWk5FMjVwVDJ5V1AxTlVuZEp4UGN2VnRmQlc0OGtQT212a1k0V2xxUDViQXdDWHdic0tyQ2drNnhic3AxMgpldz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
    - name: SecretName
      value: "IoTTwinSecret"
    - name: SecretKey
      value: "signKey"
    - name: IothubConnectionString
      value: "HostName=iot-dicom-dev-hub.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=M3PM2vdanS3QhCnjKyD8m/QObHFSR5e0ZK2wHU1Ywh8="         
  - title: "mongowriter"
    env:
    - name: LOG_TOPIC
      value: "logswrite-topic"
    - name: TELEMETRY_TOPIC
      value: "telemetrywrite-topic"
  - title: "twinlistener"
    env:
    - name: WRITE_TOPIC
      value: "telemetrywrite-topic"

replicaCount: 1

# env:
#   - name: ASPNETCORE_ENVIRONMENT
#     value: DevEU

image:
  acr: "iotimageacr.azurecr.io"
  tag: latest

