# Default values for cartonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controllers:
  - title: "analyzer"
  - title: "beapi"
    path: /cloudpillar/api
    port: 8089
  - title: "blobstreamer"
    port: 8089
    env:
    - name: BLOB_CONTAINER_NAME
      value: "iot-firmware"
    - name: IOTHUB_CONNECTION_STRING
      value: "HostName=szlabs-iot-hub.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=dMBNypodzUSWPbxTXdWaV4PxJTR3jCwehPFCQn+XJXc="
    - name: STORAGE_CONNECTION_STRING
      value: "DefaultEndpointsProtocol=https;AccountName=szlaaa12026ce;AccountKey=ZCspYG/5HjJTVdY+9Hf/ZkzHHspd2BGXH8cVPUkgDzmvA5JCyRWk5B6aFG1izNq7YC+i/VsDrxOb+AStciDLcw==;EndpointSuffix=core.windows.net"
    - name: MESSAGE_EXPIRED_MINUTES
      value: "60"
    - name: RETRY_POLICY_BASE_DELAY
      value: "2"
    - name: RETRY_POLICY_EXPONENT
      value: "3"
    # - name: PARTITION_ID
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.name
    # - name: SECRET_NAMESPACE
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.namespace
  - title: "iotlistener"
    kind: StatefulSet
    env:
    - name: LOGSWRITE_TOPIC
      value: "logswrite-topic"
    - name: IOTHUB_EVENT_HUB_COMPATIBLE_ENDPOINT
      value: "Endpoint=sb://iothub-ns-szlabs-iot-24863501-f5f2fbc92a.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=XMuOJh0spASmuLLKcdvBJ8zqjirW6XX1NAgxu1hSXf4=;EntityPath=szlabs-iot-hub"
    - name: IOTHUB_EVENT_HUB_COMPATIBLE_PATH
      value: "szlabs-iot-hub"
    - name: STORAGE_CONNECTION_STRING
      value: "DefaultEndpointsProtocol=https;AccountName=szlaaa12026ce;AccountKey=ZCspYG/5HjJTVdY+9Hf/ZkzHHspd2BGXH8cVPUkgDzmvA5JCyRWk5B6aFG1izNq7YC+i/VsDrxOb+AStciDLcw==;EndpointSuffix=core.windows.net"
    - name: BLOB_CONTAINER_NAME
      value: "iot-firmware"
    - name: BLOB_STREAMER_URL
      value: "blob-streamer"
    - name: RANGE_CALCULATE_TYPE
      value: "percent"
    - name: RANGE_PERCENT
      value: "25"
    - name: MESSAGE_TIMEOUT_MINUTES
      value: "60"
    - name: RANGE_BYTES
      value: "123456"
    - name: KUBERNETES_SERVICE_HOST
      value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQml5QWE3YVJIRkRDaDJxZ2EKOXNUVUdJTkU1akhBRm5tTTh4V2VUL3VuaTVJNHROcWhWNVh4MHBEcm1DVjltYnJvRnRmRWEwWFZmS3VNQXh4ZgpaNkxNL3lLaGdZa0RnWVlBQkFHQnpnZG5QNzk4RnNMdVdZVEREUUE3YzByM0JWazhOblJVU2V4cFFVc1JpbFBOCnYzU2NoTzBsUnc5UnU4Nngxa2huVkR4K2R1cTRCaURGY3ZsU0FjeWpMQUNKdmp2b3lUTEppQStUUUZkbXJlYXIKak1pWk5FMjVwVDJ5V1AxTlVuZEp4UGN2VnRmQlc0OGtQT212a1k0V2xxUDViQXdDWHdic0tyQ2drNnhic3AxMgpldz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
    - name: SIGNING_PEM
      value: ""
    - name: SECRET_NAME
      value: "IoTTwinSecret"
    - name: SECRET_KEY
      value: "signKey"
    - name: IOTHUB_CONNECTION_STRING
      value: "HostName=szlabs-iot-hub.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=dMBNypodzUSWPbxTXdWaV4PxJTR3jCwehPFCQn+XJXc="                
  - title: "keyholder"
    port: 8089
  - title: "mongowriter"
    env:
    - name: LOG_TOPIC
      value: "logswrite-topic"
    - name: TELEMETRY_TOPIC
      value: "telemetrywrite-topic"
  - title: "twinlistener"
    env:
    - name: WRITE_TOPIC
      value: "telemetrywrite-topic"

replicaCount: 1

# env:
#   - name: ASPNETCORE_ENVIRONMENT
#     value: DevEU

image:
  acr: "iotimageacr.azurecr.io"
  tag: latest

