# Default values for cartonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controllers:
  - title: "blobstreamer"
    path: /blobstreamer-service
    port: 8080
    env:
    - name: BlobContainerName
      value: "iotcontainer"
    - name: IothubConnectionString
      value: "HostName=cp-dev-iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=9rvwvS9LH8uF2tv30QOjqZc0u3y9UlVTjAIoTCFYTQI="
    - name: StorageConnectionString
      value: "DefaultEndpointsProtocol=https;AccountName=cpiotdevfiles;AccountKey=CSd3tecNZy82mqFfxvYB5PvoDbhQRjPWyJaMshFgz6WRshqcKURlqGKtZk2tFLQgh8VRdbCFLUqe+AStnJhc2g==;EndpointSuffix=core.windows.net"
    - name: MessageExpiredMinutes
      value: "60"
    - name: RetryPolicyBaseDelay
      value: "2"
    - name: RetryPolicyExponent
      value: "3"
    # - name: PARTITION_ID
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.name
    # - name: SECRET_NAMESPACE
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.namespace
  - title: "iotlistener"
    kind: StatefulSet
    env:
    - name: LogswriteTopic
      value: "logswrite-topic"
    - name: IothubEventHubCompatibleEndpoint
      value: "Endpoint=sb://iothub-ns-cp-dev-iot-25265827-69d8d8cde4.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=9rvwvS9LH8uF2tv30QOjqZc0u3y9UlVTjAIoTCFYTQI=;EntityPath=cp-dev-iothub"
    - name: IothubEventHubCompatiblePath
      value: "cp-dev-iothub"
    - name: StorageConnectionString
      value: "DefaultEndpointsProtocol=https;AccountName=cpiotdevfiles;AccountKey=CSd3tecNZy82mqFfxvYB5PvoDbhQRjPWyJaMshFgz6WRshqcKURlqGKtZk2tFLQgh8VRdbCFLUqe+AStnJhc2g==;EndpointSuffix=core.windows.net"
    - name: BlobContainerName
      value: "iotcontainer"
    - name: BlobStreamerUrl
      value: "blobstreamer-service"
    - name: SigningUrl
      value: "keyholder-service"
    - name: RangeCalculateType
      value: "percent"
    - name: RangePercent
      value: "25"
    - name: MessageTimeoutMinutes
      value: "60"
    - name: RangeBytes
      value: "123456"
    - name: IothubConnectionDeviceId
      value: "iothub-connection-device-id"     
  - title: "keyholder"
    path: /keyholder-service
    port: 8080
    env:
    - name: KubernetesServiceHost
      value: ""
    - name: SigningPem
      value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQml5QWE3YVJIRkRDaDJxZ2EKOXNUVUdJTkU1akhBRm5tTTh4V2VUL3VuaTVJNHROcWhWNVh4MHBEcm1DVjltYnJvRnRmRWEwWFZmS3VNQXh4ZgpaNkxNL3lLaGdZa0RnWVlBQkFHQnpnZG5QNzk4RnNMdVdZVEREUUE3YzByM0JWazhOblJVU2V4cFFVc1JpbFBOCnYzU2NoTzBsUnc5UnU4Nngxa2huVkR4K2R1cTRCaURGY3ZsU0FjeWpMQUNKdmp2b3lUTEppQStUUUZkbXJlYXIKak1pWk5FMjVwVDJ5V1AxTlVuZEp4UGN2VnRmQlc0OGtQT212a1k0V2xxUDViQXdDWHdic0tyQ2drNnhic3AxMgpldz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
    - name: SecretName
      value: "IoTTwinSecret"
    - name: SecretKey
      value: "signKey"
    - name: IothubConnectionString
      value: "HostName=cp-dev-iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=9rvwvS9LH8uF2tv30QOjqZc0u3y9UlVTjAIoTCFYTQI="

replicaCount: 1

# env:
#   - name: ASPNETCORE_ENVIRONMENT
#     value: DevEU

image:
  acr: "cpdevacr.azurecr.io"
  tag: latest

