# Default values for cartonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controllers:
  - title: "blobstreamer"
    replicaCount: 3
    path: /blobstreamer-service
    port: 8081
    env:
    - name: BlobContainerName
      value: "iotcontainer"
    - name: IothubConnectionString
      value: "HostName=cp-dev-iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=MUEZMQwZ6IK1WeEsLNM7Egb/vFb5NKS1vAIoTEK8D/M="
    - name: StorageConnectionString
      value: "DefaultEndpointsProtocol=https;AccountName=cpiotdevfiles;AccountKey=4xnzVu7YbBcaclEdyoQnR1Ej7z51cOYWIsnnocN7X6UOP4xNN523FNntSKM8NhBscybkvIxdl+rz+AStree0GA==;EndpointSuffix=core.windows.net"
    - name: MessageExpiredMinutes
      value: "60"
    - name: RetryPolicyBaseDelay
      value: "20"
    - name: RetryPolicyExponent
      value: "30"
    # - name: PARTITION_ID
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.name
    # - name: SECRET_NAMESPACE
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.namespace
  - title: "iotlistener"
    kind: StatefulSet
    env:
    - name: LogswriteTopic
      value: "logswrite-topic"
    - name: IothubEventHubCompatibleEndpoint
      value: "Endpoint=sb://iothub-ns-cp-dev-iot-25287979-68405f75ab.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=MUEZMQwZ6IK1WeEsLNM7Egb/vFb5NKS1vAIoTEK8D/M=;EntityPath=cp-dev-iothub"
    - name: IothubEventHubCompatiblePath
      value: "cp-dev-iothub"
    - name: StorageConnectionString
      value: "DefaultEndpointsProtocol=https;AccountName=cpiotdevfiles;AccountKey=4xnzVu7YbBcaclEdyoQnR1Ej7z51cOYWIsnnocN7X6UOP4xNN523FNntSKM8NhBscybkvIxdl+rz+AStree0GA==;EndpointSuffix=core.windows.net"
    - name: BlobContainerName
      value: "iotcontainer"
    - name: BlobStreamerUrl
      value: "http://blobstreamer-service:8081/"
    - name: KeyHolderUrl
      value: "http://keyholder-service:8082/"
    - name: BEApiUrl
      value: "http://keyholder-service:8083/"
    - name: RangeCalculateType
      value: "percent"
    - name: RangePercent
      value: "25"
    - name: MessageTimeoutMinutes
      value: "60"
    - name: RangeBytes
      value: "123456"
    - name: IothubConnectionDeviceId
      value: "iothub-connection-device-id"     
  - title: "keyholder"
    path: /keyholder-service
    port: 8082
    env:
    - name: KubernetesServiceHost
      value: ""
    - name: SigningPem
      value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQml5QWE3YVJIRkRDaDJxZ2EKOXNUVUdJTkU1akhBRm5tTTh4V2VUL3VuaTVJNHROcWhWNVh4MHBEcm1DVjltYnJvRnRmRWEwWFZmS3VNQXh4ZgpaNkxNL3lLaGdZa0RnWVlBQkFHQnpnZG5QNzk4RnNMdVdZVEREUUE3YzByM0JWazhOblJVU2V4cFFVc1JpbFBOCnYzU2NoTzBsUnc5UnU4Nngxa2huVkR4K2R1cTRCaURGY3ZsU0FjeWpMQUNKdmp2b3lUTEppQStUUUZkbXJlYXIKak1pWk5FMjVwVDJ5V1AxTlVuZEp4UGN2VnRmQlc0OGtQT212a1k0V2xxUDViQXdDWHdic0tyQ2drNnhic3AxMgpldz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
    - name: SecretName
      value: "IoTTwinSecret"
    - name: SecretKey
      value: "signKey"
    - name: IothubConnectionString
      value: "HostName=cp-dev-iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=MUEZMQwZ6IK1WeEsLNM7Egb/vFb5NKS1vAIoTEK8D/M="
    - name: DPSConnectionString
      value: "HostName=cp-dev-dps.azure-devices-provisioning.net;SharedAccessKeyName=provisioningserviceowner;SharedAccessKey=OvCnPzeHY0yu211bWFmtWmxzvKz2jNYje3bUbDCOQDg="
    - name: DPSIdScope
      value: "0ne00B51BC7"
    - name: GlobalDeviceEndpoint
      value: "global.azure-devices-provisioning.net"
    volumeMounts:
    - name: devbe-cert
      mountPath: "/mnt/devbe-cert"
      readOnly: true
  - title: "beapi"
    replicaCount: 3
    path: /beapi-service
    port: 8083
    env:
    - name: IothubConnectionString
      value: "HostName=cp-dev-iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=MUEZMQwZ6IK1WeEsLNM7Egb/vFb5NKS1vAIoTEK8D/M="
    - name: DPSConnectionString
      value: "HostName=cp-dev-dps.azure-devices-provisioning.net;SharedAccessKeyName=provisioningserviceowner;SharedAccessKey=OvCnPzeHY0yu211bWFmtWmxzvKz2jNYje3bUbDCOQDg="
    - name: DPSIdScope
      value: "0ne00B51BC7"
    - name: GlobalDeviceEndpoint
      value: "global.azure-devices-provisioning.net"
    - name: ExpirationCertificatePercent
      value: "0.6"
    - name: "maxCountOfDevices"
      value: "100"
    
replicaCount: 1

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Dev

image:
  acr: "cpdevacr.azurecr.io"
  tag: latest

