# traefik.toml
[tls]

  [[tls.certificates]]
    certFile = "/ssl/certificate.pem"
    keyFile = "/ssl/certificate.key"
[tls.stores]
  [tls.stores.Store0]
    [tls.stores.Store0.defaultCertificate]
      certFile = "/ssl/certificate.pem"
      keyFile = "/ssl/certificate.key"
