apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: {env}be-cert
spec:
  output:
    secret:
      dataKey: data
      name: {env}be-cert
      type: kubernetes.io/tls
  vault:
    name: cp-{env}be-kv
    object:
      name: {cert}
      type: secret
