name: selective_ci_$(Rev:.r)
# name: selective_ci


# 1. The branch trigger should be chnages in the current branch
trigger:
  batch: true
  branches:
    include:
    - main
    - test-selective-build
    - TestBranch
    - "*"
    # - $(Build.SourceBranchName)
    # - main
    # - *
  # paths:
  #   include:
  #   - src/backend/*
# 2. The pipeline should be triggered on every change in the repository
# pr: none


parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd
  - name: image
    displayName: Select Image to Build and Scan
    type: string
    default: iotlistener
    values:
    # - all
    - analyzer
    - beapi
    - blobstreamer
    - iotlistener
    - keyholder
    - mongowriter
    - twinlistener
  - name: versionString
    displayName: Select Major & Minor Verson
    type: string
    default: latest # 1.0
    values:
    - latest # 1.0
    - nextminor # 1.1
    - nextmajor #2.0

# * Variables
variables:
#* Variable Groups
- group: arm-vg
- group: iac-backend-vg
- group: aks-backend-vg
- group: backend-secrets-vg

#* Dynamic Variables
- name: TIMESTAMP
  value: $(date +%Y%m%d%H%M%S)
- name: BuildNumber
  value: $(git rev-list --count HEAD)
- name: RepoName
  value: $(Build.Repository.Name)
# - name: RepoName2
#   value: $(git config --get remote.origin.url | sed 's/.*\///')
- name: SourceBranchName
  value: $(Build.SourceBranchName)
- name: DockerBasePath
  value: src/backend
  # value: src/backend
  # value: $(git diff --name-only origin/main..$(Build.SourceBranchName))
  # value: $(git diff --name-only HEAD~1..$(Build.SourceBranchName))
  # value: $(git diff --name-only HEAD~1..$(Build.SourceBranchName))



stages:
- stage: Test
  displayName: Test_Stage
  jobs:
  - job: ADO_Repo
    displayName: Print ADO Repo
    pool:
      name: $(AGENT_POOL)
      agent.name: aks-${{parameters.env}}-agent
    steps:
    - checkout: self
      persistCredentials: true
      # This Step will print the Repo Name, Source Branch Name (from ADO), Current Branch Name (Locally), changed files names and path to the console
    - bash: |
        
        echo -e "\n========================================\n\t ADO Started\n========================================\n"        
        echo "Repo Name: $(RepoName)"
        echo "Source Branch Name: $(SourceBranchName)"
        echo -e "Path: $PWD\n"
        echo $PWD
        echo -e "Local Path: $(Build.Repository.LocalPath)\n"
        echo -e "Docker Base Path: $(DockerBasePath)\n"

        
        
        git fetch --all
        git merge-base origin/main $(SourceBranchName)
        git checkout $BRANCH

        FILES=$(git diff --name-only origin/main..$(SourceBranchName)) # Changed Files Names and Path

        echo -e "\n\nChanged Files Names and Path: \n----------------------------------------------------\n"
        echo "${FILES[@]}"
        # echo "Changed Files Names and Path2: $(Files)"

        # DockerBasePath=$(echo $(Build.Repository.LocalPath)/src/backend) 
        DOCKER_BASE_PATH=$(DockerBasePath) 
        echo $DOCKER_BASE_PATH
        echo -e "\n========================================\n\t File By File1\n========================================\n"

        git diff --name-only origin/main..$(SourceBranchName) | while read -r file; do
          filename=$(basename "$file")
          lower_filename=$(echo "$filename" | tr '[:upper:]' '[:lower:]')
          if [[ $file == *$DOCKER_BASE_PATH* ]]; then
            # echo -e "\n\n"
            # echo "YES!!!!!!!!!!!!!!! $file contains $DOCKER_BASE_PATH !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 
            echo "File Changed: $filename"
            # Check if filename as lower string contain the image name as lower string
            IMAGE=$(image)
            echo $IMAGE
            
            if [[ $lower_filename == *$IMAGE.csproj ]]; then
              echo "YES ! $filename contains $IMAGE" 
            else
              # echo "NO ! $filename does not contain $IMAGE" 
            fi
          else
            # echo "NO ! $file does not contain $DOCKER_BASE_PATH" 
          fi
        done

      name: print_ado_repo
          