name: selective_ci

trigger:
- none
  # # batch: true
  # branches:
  #   include:
  #   - main
  #   - test-selective-build
  #   - TestBranch

parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd
  - name: image

    displayName: Select Image to Build and Scan
    type: string
    default: iotlistener
    values:
    # - all
    - analyzer
    - beapi
    - blobstreamer
    - iotlistener
    - keyholder
    - mongowriter
    - twinlistener
  - name: versionString
    displayName: Select Major & Minor Verson
    type: string
    default: latest # 1.0
    values:
    - latest # 1.0
    - nextminor # 1.1
    - nextmajor #2.0

# * Variables
variables:
#* Variable Groups
- group: arm-vg
- group: iac-backend-vg
- group: aks-backend-vg
- group: backend-secrets-vg

#* Dynamic Variables
- name: TIMESTAMP
  value: $(date +%Y%m%d%H%M%S)
- name: BuildNumber
  value: $(git rev-list --count HEAD)



stages:
- stage: Test
  displayName: Test_Stage
  jobs:
  - job: Local_Repo
    displayName: 'Print Local Repo'
    pool:
      name: $(AGENT_POOL)
      agent.name: aks-${{parameters.env}}-agent
      steps:
      - checkout: self
        persistCredentials: true
      # This Step will print the Repo Name, Source Branch Name (from ADO), Current Branch Name (Locally), changed files names and path to the console
      - bash: |
          echo "Local"
        name: print_local_repo