
name: iac_backend_infra
trigger:
  - none

# variables:


stages:
- stage: Validate_Files
  displayName: Validate Cloned Repo Files
  jobs: 
  - job: Validate_Backend_Files
    displayName: Validate IaC Backend Files Existence
    pool:
      vmImage: 'ubuntu-20.04'    
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: Bash@3
      displayName: 'Validate IaC Pipelines Folder & Files Existence'
      inputs:
        targetType: inline
        script: |
          if [ ! -d iac/ ] || [ ! -d iac/pipelines/ ] || [ ! -f iac/pipelines/backend-infra.yml ]; then
            echo "Missing - IaC Pipelines Folder Or Files is Missing"
            exit 1
          fi
          echo "IaC & Pipelines Folders Exists"

    - task: Bash@3
      displayName: 'Validate TerraForm Backend Files'
      inputs:
        targetType: inline
        script: |
          if [ ! -d iac/terraform/backend ]; then
            echo "Folder - Terraform Backend Folder is Missing"
            exit 1
          elif [ ! -d iac/terraform/backend/terraform.tfstate.d ] || [ ! -f iac/terraform/backend/0-backend-variables.tf ] || [ ! -f iac/terraform/backend/1-main.tf ] || [ ! -f iac/terraform/backend/2-providers.tf ] || [ ! -f iac/terraform/backend/tf-backend-init.sh ] || [ ! -f iac/terraform/backend/tf-backend-apply.sh ]; then
            missing_files=()
            if [ ! -d iac/terraform/backend/terraform.tfstate.d ]; then
              missing_files+=("terraform.tfstate.d")
            fi
            if [ ! -f iac/terraform/backend/0-backend-variables.tf ]; then
              missing_files+=("0-backend-variables.tf")
            fi
            
            if [ ! -f iac/terraform/backend/1-main.tf ]; then
              missing_files+=("1-main.tf")
            fi
            
            if [ ! -f iac/terraform/backend/2-providers.tf ]; then
              missing_files+=("2-providers.tf")
            fi
            
            if [ ! -f iac/terraform/backend/tf-backend-init.sh ]; then
              missing_files+=("tf-backend-init.sh")
            fi
            
            if [ ! -f iac/terraform/backend/tf-backend-apply.sh ]; then
              missing_files+=("tf-backend-apply.sh")
            fi
            
            echo "One or more files are missing in the TF Backend directory (iac/terraform/backend/): ${missing_files[*]}"
            exit 1          
          
          elif 
          fi
          echo "Terraform Backend Folder & Files Exists"

