
name: iac_backend_infra
trigger:
  - none

# variables:


stages:
- stage: Validate_Files
  displayName: Validate Cloned Repo Files
  jobs: 
  - job: Validate_Backend_Files
    displayName: Validate IaC Backend Files Existence
    pool:
      vmImage: 'ubuntu-20.04'    
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: Bash@3
      displayName: 'Validate IaC & Pipelines Folder Existence'
      inputs:
        targetType: inline
        script: |
          if [ ! -d iac/ ] || [ ! -d iac/pipelines/ ]; then
            echo "Folder - IaC  Or Pipelines Folder is Missing"
            exit 1
          fi
          echo "IaC & Pipelines Folders Exists"
