
name: iac_backend_infra
trigger:
  - none

# variables:

jobs:

- job: Clone_Code
  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - bash: |
      ls -la
      cat backend-infra.yml
    name: "bash"
    workingDirectory: 'iac/pipelines'