# 1. My pipelin


name: selective_ci_$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - main
    - test-selective-build
    - testselbuild
    - "*"

parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd
  - name: image
    displayName: Select Image to Build and Scan
    type: string
    default: all
    values:
    - analyzer
    - beapi
    - blobstreamer
    - iotlistener
    - keyholder
    - mongowriter
    - twinlistener    
    - all

variables:
  # -name: isMain
    # value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
# - name: isAuto
  # value: $[eq('${{ image }}', 'all')]
- name: TIME
  value: $(date +%Y%m%d%H%M%S)
- name: GitBuildNumber
  value: $(git rev-list --count HEAD)
- name: major
  value: $(grep -oP '^major=\K\d+' src/backend/version.txt)
- name: minor
  value: $(grep -oP '^minor=\K\d+' src/backend/version.txt)
- name: ChosenImage
  value: 'iotlistener'



stages:
- stage: BuildSpecificImage
  displayName: Build Specific Image
  condition: ne('${{ parameters.image }}', 'all')
  pool:
    name: $(AGENT_POOL)
    agent.name: aks-${{parameters.env}}-agent
  jobs:
  - job: Manual_Build
    displayName: Build ${{ parameters.image }}
    steps:
    - script: echo "Manual Building ${{ parameters.image }}" # Replace with your build command
  - job: Manual_Scan
    displayName: Scan ${{ parameters.image }}
    steps:
    - script: echo "Manual Scanning ${{ parameters.image }}" # Replace with your scan command
  - job: Manual_Push
    displayName: Push ${{ parameters.image }}
    steps:
    - script: echo "Manual Pushing ${{ parameters.image }}" # Replace with your push command


- stage: BuildAllImages
  displayName: Build All Images
  condition: eq('${{ parameters.image }}', 'all')
  pool:
    name: $(AGENT_POOL)
    agent.name: aks-${{parameters.env}}-agent
  jobs:
  # Jobs to build all images except "all"
  - job: Auto_Build
    displayName: Build ${{ parameters.image }}
    steps:
    - script: echo "Auto Building ${{ parameters.image }}" # Replace with your build command
  - job: Auto_Scan
    displayName: Scan ${{ parameters.image }}
    steps:
    - script: echo "Auto Scanning ${{ parameters.image }}" # Replace with your scan command
  - job: Auto_Push
    displayName: Push ${{ parameters.image }}
    steps:
    - script: echo "Auto Pushing ${{ parameters.image }}" # Replace with your push command