name: ci_build_t_9320_2
trigger:
- $(Build.SourceBranchName)


parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd
  - name: image
    displayName: Select Image to Build and Scan
    type: string
    default: iotlistener
    values:
    # - all
    - analyzer
    - beapi
    - blobstreamer
    - iotlistener
    - keyholder
    - mongowriter
    - twinlistener  
  - name: versionString
    displayName: Select Major & Minor Verson
    type: string
    default: current # 1.0
    values:
    - current # 1.0
    - nextminor # 1.1
    - nextmajor #2.0
  - name: chosenVersion
    displayName: Select Major & Minor Verson
    type: string
    default: 8.3
    values:
    - 8.3
    - 8.4
    - 9.0


variables:
- group: arm-vg
- group: iac-backend-vg
- group: aks-backend-vg
- group: backend-secrets-vg

- name: TIMESTAMP
  value: $(date +%Y%m%d%H%M%S)
- name: BuildNumber
  value: $(git rev-list --count HEAD)

- name: chosenMajor # Major (Based on User Selection)
  value: ${{ coalesce(split(parameters.chosenVersion, '.')[0], '1') }}
- name: chosenMinor # Minor (Based on User Selection)
  value: ${{ coalesce(split(parameters.chosenVersion, '.')[1], '0') }}
- name: chosenVersion # Minor (Based on User Selection)
  value: ${{ parameters.chosenVersion }}

- name: currentMajor # Major (Based on User Selection)
  value: 1
  # value: $(grep -oP '^major=\K\d+' src/backend/version.txt)
- name: currentMinor # Minor (Based on User Selection)
  value: 0
- name: currentVersion # Version (Based on User Selection)
  value: 1.0
  # value: $(grep -oP '^major=\K\d+' src/backend/version.txt).$(grep -oP '^minor=\K\d+' src/backend/version.txt)



stages:
- stage: CI_Build
  displayName: CI Build Process
  # variables:
    # currentVersion: $(currentMajor).$(currentMinor)
    # chosenVersion: $(chosenMajor).$(chosenMinor)
    # versionF: $(major).$(minor).$(BuildNumber).$(TIMESTAMP)
  jobs:
  - job: Update_Version
    displayName: Update Variables
    pool:
      name: $(AGENT_POOL)
      agent.name: aks-${{parameters.env}}-agent 
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - bash: |
        echo "##[section]Chosen Group"
        echo "##[group]Chosen Group"
        echo "##[command]chosenMajor:   $(chosenMajor)"
        echo "##[command]chosenMinor:   $(chosenMinor)"
        echo "##[command]chosenVersion:   $(chosenVersion)"
        echo "##[endgroup]Chosen Group Finished"



        echo "##[section]Current Group"
        echo "##[group]Current Group"
        echo "##[command]currentMajor:   $(currentMajor)"
        echo "##[command]currentMinor:   $(currentMinor)"
        echo "##[command]currentVersion:   $(currentVersion)"
        echo "##[endgroup]Current Group Finished"
#           echo "##vso[task.setvariable variable=version;isOutput=true]$NewVersion"
  
#           echo "##[warning]NewVersion  =  major.minor.buildnumber.timestamp"
#           echo "##[command]NewVersion  =  $NewVersion"

      name: CompareVersions