
name: ci_clean_$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - "*"

variables:
- name: basePath
  value: src/backend/
- name: dockerFile
  value: infra/build/Dockerfile
- name: major
  value: $(grep -oP '^major=\K\d+' src/backend/version.txt)
- name: minor
  value: $(grep -oP '^minor=\K\d+' src/backend/version.txt)
- name: TIME
  value: $(date +%Y%m%d%H%M%S)
- name: GitBuildNumber
  value: $(git rev-list --count HEAD)
- name: registryName
  value: 'iotimageacr'
- name: dockerfilePath
  value: './src/edge/conquest/Dockerfile'
- name: pipelineAcrConnection
  value: 'iotacr'


parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd    
- name: image
  displayName: Select Image to Build and Scan
  type: string
  default: all
  values:
  - analyzer
  - beapi
  - blobstreamer
  - iotlistener
  - keyholder
  - mongowriter
  - twinlistener    
  - edge_conquest

resources:
- repo: self

stages:
- stage: BuildSpecificImage
  displayName: Build Specific Image
  condition: ne('${{ parameters.image }}', 'all')
  jobs:
  - job: ConquestManualBuildTagScanPush
    condition: eq('${{ parameters.image }}', 'edge_conquest')    
      displayName: Build, Tag, Scan, and Push
      variables:
        imageName: 'edge_conquest'
        imageVersion: 'v0.7.3'
        registryName: 'iotimageacr'
        dockerfilePath: './src/edge/conquest/Dockerfile'
        pipelineAcrConnection: 'iotacr'
        stages:
        - stage: Build
          displayName: Build and push
          jobs:  
          - job: Build
            displayName: Build
            pool:
              vmImage: 'ubuntu-latest'
            steps:
            - task: Docker@2
              displayName: 'Build and Push Image'
              inputs:
                command: 'buildAndPush'
                repository: '$(registryName).azurecr.io/$(imageName)'
                dockerfile: '$(dockerfilePath)'
                containerRegistry: '$(pipelineAcrConnection)'
                tags: '$(imageVersion)'