
name: ci_clean_$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - "*"

variables:
- name: basePath
  value: src/backend/
- name: dockerFile 
  value: infra/build/Dockerfile
- name: major
  value: $(grep -oP '^major=\K\d+' src/backend/version.txt)
- name: minor
  value: $(grep -oP '^minor=\K\d+' src/backend/version.txt)

parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd    
- name: image
  displayName: Select Image to Build and Scan
  type: string
  default: all
  values:
  - analyzer
  - beapi
  - blobstreamer
  - iotlistener
  - keyholder
  - mongowriter
  - twinlistener    
  - edge_conquest

# - template: templates/images-template.yml
- template: images-template.yml


stages:
- stage: BuildSpecificImage
  displayName: Build Specific Image
  condition: ne('${{ parameters.image }}', 'all')
  jobs:
  - job: Manual_Build
    displayName: Build ${{ image }}
    steps:
    - script: echo "Manual Building ${{ image }}" # Replace with your build command
  - job: Manual_Scan
    displayName: Scan ${{ image }}
    steps:
    - script: echo "Manual Scanning ${{ image }}" # Replace with your scan command
  - job: Manual_Push
    displayName: Push ${{ image }}
    steps:
    - script: echo "Manual Pushing ${{ image }}" # Replace with your push command

- stage: BuildAllImages
  displayName: Build All Images
  condition: eq('${{ parameters.image }}', 'all')
  jobs:
    # Add the jobs to build, scan, and push all images
    - ${{ each image in parameters.images }}:
      - script: |
          echo "Building ${{ image.name }}" # Replace with your build command
          echo "Path: ${{ image.path }}" # Path to the image
          # Add scan and push commands as needed
