stages:
- stage: CI_Build
  displayName: CI Build Process

  jobs:
  - job: Update_Version
    displayName: Update Version ID
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - bash: |
        echo "##[section]Update Version Section"
        echo "##[group]Get Current Version Group"

        # +TODO-Uncomment echo "##vso[task.setvariable variable=currentmajor;isoutput=true]$(grep -oP '^major=\K\d+' src/backend/version.txt)"
        echo "##vso[task.setvariable variable=currentmajor;isoutput=true]1"
        echo "currentmajor: $(currentmajor)"

        # +TODO-Uncomment echo "##vso[task.setvariable variable=currentminor;isoutput=true]$(grep -oP '^minor=\K\d+' src/backend/version.txt)"
        echo "##vso[task.setvariable variable=currentminor;isoutput=true]0"
        echo "currentminor: $(currentminor)"

        echo "##[endgroup]Get Current Version Finished"
      name: SetCurrentVersion
    - bash: |
        echo "##[section]Update Version Section"
        echo "##[group]Get Current Version Group"

        # +TODO-Uncomment echo "##vso[task.setvariable variable=currentmajor;isoutput=true]$(grep -oP '^major=\K\d+' src/backend/version.txt)"
        echo "##vso[task.setvariable variable=currentmajor;isoutput=true]1"
        echo "currentmajor: $(currentmajor)"

        # +TODO-Uncomment echo "##vso[task.setvariable variable=currentminor;isoutput=true]$(grep -oP '^minor=\K\d+' src/backend/version.txt)"
        echo "##vso[task.setvariable variable=currentminor;isoutput=true]0"
        echo "currentminor: $(currentminor)"

        echo "##[endgroup]Get Current Version Finished"
      name: SetCurrentVersion2