
name: ci_build

trigger:
# - $(Build.SourceBranchName)
- "TestBranch"



parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd

variables:
- group: arm-vg
# resources:
# - repo: self
#   ref: $(Build.SourceBranchName)


resources:
  repositories:
  - repository: CloudPillar
    type: git
    name: CloudPillar/CloudPillar
    ref: $(Build.SourceBranch)

steps:
- checkout: CloudPillar


stages:
- stage: Versioning
  displayName: 'Versioning Update Process'
  jobs:
  - job: GetFileChanges
    displayName: Getting Changed Files 
    pool:
      name: $(AGENT_POOL)
      agent.name: aks-${{parameters.env}}-agent 
    steps:
    - checkout: CloudPillar
    # - checkout: self
    # - checkout: git://CloudPillar@CloudPillar$(Build.SourceBranch)
      persistCredentials: true
      clean: true
    - task: Bash@3
      displayName: Get Changed Files
      inputs:
        targetType: inline
        script: |
          SourceBranch=$(Build.SourceBranchName)
          echo "Source Branch Name: $(Build.SourceBranchName)"
          
          git checkout --force $(Build.SourceBranchName)
          CurrentBranch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current Branch Name: $CurrentBranch"

          differences=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
          echo "Differences: $differences"

          printf "Tree:\n"
          tree ./














































