
name: ci_build

trigger:
- $(Build.SourceBranchName)



parameters:
  - name: env
    displayName: Select Environment to deploy
    type: string
    default: dev
    values:
    - tst
    - dev
    - stg
    - prd

variables:
- group: arm-vg

# resources:
#   repositories:
#   - repository: CloudPillar
#     name: self
#     ref: $(Build.SourceBranchName)

stages:
- stage: Versioning
  displayName: 'Versioning Update Process'
  jobs:
  - job: GetFileChanges
    displayName: Getting Changed Files 
    pool:
      name: $(AGENT_POOL)
      agent.name: aks-${{parameters.env}}-agent 
    steps:
    - checkout: self
    # - checkout: CloudPillar
    # - checkout: git://CloudPillar@CloudPillar$(Build.SourceBranch)
      persistCredentials: true
      clean: true
    - task: Bash@3
      displayName: Get Changed Files
      inputs:
        targetType: inline
        script: |
          
          SourceBranch=$(Build.SourceBranchName)
          CurrentBranch=$(git rev-parse --abbrev-ref HEAD)

          echo "Source Branch Name: $(Build.SourceBranchName)"
          echo "Current Branch Name: $CurrentBranch"

          # git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion)
          # git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion)
          differences=$(git diff-tree --no-commit-id --name-only -r $CurrentBranch)
          echo "Differences: $differences"

          printf "Tree:\n"
          tree ./














































