apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: int-cert
  namespace: traefik
spec:
  output:
    secret:
      dataKey: data
      name: int-cert
    transform:
    - base64decode
  vault:
    name: cp-{env}be-kv
    object:
      name: {cert}
      type: secret