apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: {env}be-cert
  namespace: traefik
spec:
  output:
    secret:
      dataKey: data
      name: {env}be-cert
    transform:
    - base64decode
   vault:
    name: cp-{env}be-kv
    object:
      name: {cert}
      type: secret