service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #external-dns.alpha.kubernetes.io/hostname: {host}
  enabled: "true"

additionalArguments:
  - "--providers.file.filename=/config/traefik.toml"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--ping=true"

additionalVolumeMounts:
- name: ssl
  mountPath: /ssl
 
volumes:
  - name: traefik-config
    mountPath: /config
    type: configMap

deployment:
  replicas: 4
  podAnnotations:
    openservicemesh.io/inbound-port-exclusion-list: "8443"
  initContainers:
  - image: alpine/openssl
    name: convert-certs
    command: ['sh', '-c', 'openssl pkcs12 -in /certs/data -nocerts -out /ssl/key.pem -passin pass:"" -passout pass:1234 &&
    openssl rsa -in /ssl/key.pem -out /ssl/certificate.key -passin pass:1234 && 
    openssl pkcs12 -in /certs/data -clcerts -nokeys -out /ssl/cert.pem -passin pass:"" && openssl pkcs12 -in /certs/data -cacerts -nokeys -out /ssl/ca.pem -passin pass:"" &&
    cat /ssl/cert.pem /ssl/ca.pem > /ssl/certificate.pem && rm /ssl/cert.pem /ssl/ca.pem /ssl/key.pem']
    volumeMounts:
    - name: certs
      mountPath: /certs
      readOnly: true
    - name: ssl
      mountPath: /ssl
  additionalVolumes:
  - name: ssl
    emptyDir: {}
  - name: certs
    secret:
      defaultMode: 420
      optional: false
      secretName: devbe-cert
      
livenessProbe:
  httpGet:
    path: /ping
    port: 9000
  initialDelaySeconds: 10
  periodSeconds: 10